### ISSUE TITLE
some messages are not received when sending a lot of messages fast

### ISSUE THREAD

**Issue by tcoopman** [anmonteiro/httpun-ws#20]
I'm testing this with re-web, but I'm pretty sure the error is in `websocketaf`, because I checked at the level where the messages enter in [re-web](https://github.com/yawaramin/re-web/blob/4a8bce346627613694a26f7d38773d251fc106fb/ReWeb/Server.ml#L72) (@yawaramin) 

So what I do is this: I'm sending 8 messages in a row (without waiting). I see that these messages are pushed (checked with both firefox and chrome) in the dev tools.

What happens is that `re-web` receives only a few of the messages (sometimes all, sometimes only 1 or 2).

So for example, I send: `"A", "B", "C", "D", "E", "F", "G"`.
`re-web` gets `"A", "B", "C"`

when I send new messages, what happens most of the time is that re-web now first receives `"D"` like it got stuck somewhere but is now received because more messages have arrived. This is only for `"D"` though, `"E", "F", "G"` are lost.

Extra info:

* When I make the message longer like: `"AAAAAAAAAAAAAAAAA"` the same things keep happening
* sometimes the server crashes (this might be re-web) with: 
```
Fatal error: exception (Failure "cannot write to closed writer")
Raised at file "string.ml", line 115, characters 19-34
Called from file "sexp.ml", line 112, characters 13-47
```

**Comment by tcoopman** [comment]
I'm going to try to reproduce with one of the examples, but I can't get the project to build with `esy` at the moment...

(First ran into: https://github.com/esy/esy/issues/1090)

```
error: build failed with exit code: 1
  build log:
    # esy-build-package: building: @opam/websocketaf@link-dev:./websocketaf.opam
    # esy-build-package: pwd: /home/thomas/Workspace/githubclones/websocketaf/_esy/default/store/b/opam__s__websocketaf-b1928d76
    # esy-build-package: running: 'dune' 'build' '-p' 'websocketaf' '-j' '4'
          ocamlc lib/.websocketaf.objs/byte/websocketaf__Handshake.{cmi,cmo,cmt} (exit 2)
    (cd _build/default && /home/thomas/.esy/3___________________________________________________________________/i/ocaml-4.10.0-e4568572/bin/ocamlc.opt -w -40 -safe-string -g -bin-annot -I lib/.websocketaf.objs/byte -I /home/thomas/.esy/3___________________________________________________________________/i/opam__s__angstrom-opam__c__0.14.1-bd038229/lib/angstrom -I /home/thomas/.esy/3___________________________________________________________________/i/opam__s__base64-opam__c__3.4.0-2495c756/lib/base64 -I /home/thomas/.esy/3___________________________________________________________________/i/opam__s__bigarray_compat-opam__c__1.0.0-9ecba1ae/lib/bigarray-compat -I /home/thomas/.esy/3___________________________________________________________________/i/opam__s__bigstringaf-opam__c__0.6.1-b73d7af1/lib/bigstringaf -I /home/thomas/.esy/3___________________________________________________________________/i/opam__s__faraday-opam__c__0.7.1-067c1217/lib/faraday -I /home/thomas/.esy/3___________________________________________________________________/i/opam__s__gluten-opam__c__0.2.1-104ebb45/lib/gluten -I /home/thomas/.esy/3___________________________________________________________________/i/opam__s__httpaf-opam__c__0.6.6-95b036b1/lib/httpaf -I /home/thomas/.esy/3___________________________________________________________________/i/opam__s__ocamlfind-opam__c__1.8.1-c7c7ac83/lib/bytes -I /home/thomas/.esy/3___________________________________________________________________/i/opam__s__result-opam__c__1.5-d9a0c062/lib/result -no-alias-deps -open Websocketaf__ -o lib/.websocketaf.objs/byte/websocketaf__Handshake.cmo -c -impl lib/handshake.ml)
    File "lib/handshake.ml", line 123, characters 4-36:
    123 |     Httpaf.Reqd.respond_with_upgrade reqd (Headers.add_list headers upgrade_headers) upgrade_handler;
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    Error: Unbound value Httpaf.Reqd.respond_with_upgrade
    error: command failed: 'dune' 'build' '-p' 'websocketaf' '-j' '4' (exited with 1)
    esy-build-package: exiting with errors above...
    
  building @opam/websocketaf@link-dev:./websocketaf.opam
esy: exiting due to errors above

```

Going to see if I can fix that

**Comment by tcoopman** [comment]
It took me a lot of messing with resolutions but I finally was able to build the examples and test that.

This is a reproduction file:

```index.html
<!DOCTYPE html>
<html>
  <head> </head>

  <body>
    <h1>websocket tests</h1>
    <script type="text/javascript">
      window.addEventListener("DOMContentLoaded", (event) => {
        console.log("DOM loaded, started ws");
        var ws = new WebSocket("ws://localhost:8080");

        ws.onopen = function () {
          // Web Socket is connected, send data using send()
          console.log("websocket connected");
          ws.send("A");
          ws.send("B");
          ws.send("C");
          ws.send("D");
          ws.send("E");
          ws.send("F");
          ws.send("G");
          ws.send("H");
          ws.send("I");
        };

        ws.onmessage = function (evt) {
          var received_msg = evt.data;

          console.log("received the message:", received_msg);
        };

        ws.onclose = function () {
          console.log("socket has closed");
        };
      });
    </script>
  </body>
</html>
```

You'll see in the console.log that you don't get all messages back when running with `lwt/echo_server_upgrade`

**Comment by anmonteiro** [comment]
Hey @tcoopman, thanks for the clear repro. I've fixed this in #21.

An additional note: if you run `nix-shell --pure` at the root of the repo (after installing [Nix](https://nixos.org/nix/)) you'll get into a shell that has the complete environment you need to run the project. No need to mess with resolutions or anything.

**Comment by tcoopman** [comment]
Thanks for the quick fix.

About nix, I've already looked at nix but decided I wouldn't put too much time into it, and now you're going to pull me back in ;-)

Anyway to have the fix in re-web I'll probably need some resolution so I'm going to see...

**Comment by yawaramin** [comment]
Wow, that was super quick 🚀 

@tcoopman I haven't tried but I think it should be enough to add a resolution for websocketaf latest commit.

**Comment by tcoopman** [comment]
I'll try tomorrow but when trying to build it earlier I got issues with httpaf. It seemed to pull in the original repo which doesn't have some methods

**Comment by anmonteiro** [comment]
It's unfortunate that esy won't install the `pin-depends` that are specified in the OPAM files.
