### ISSUE TITLE
No way to not set FIN bit on outgoing frames

### ISSUE THREAD

**Issue by aantron** [anmonteiro/httpun-ws#33]
AFAICT, from the user's point of view, writing is done through [`Wsd.t`](https://github.com/anmonteiro/websocketaf/blob/248a2cb0dcffa51996c3ad7643577dce75d67454/lib/websocketaf.mli#L135-L149), but the `FIN` bit is not exposed in the function signatures, and all calls to lower-level functions have it hardcoded to `true`:

https://github.com/anmonteiro/websocketaf/blob/248a2cb0dcffa51996c3ad7643577dce75d67454/lib/wsd.ml#L42-L45

https://github.com/anmonteiro/websocketaf/blob/248a2cb0dcffa51996c3ad7643577dce75d67454/lib/wsd.ml#L47-L50

If that's correct, it looks like `~is_fin` just needs to be propagated to the functions in `Wsd`.

**Comment by anmonteiro** [comment]
fixed in https://github.com/anmonteiro/websocketaf/pull/57
