### ISSUE TITLE
No way to send data with ping and pong

### ISSUE THREAD

**Issue by aantron** [anmonteiro/httpun-ws#36]
The [RFC](https://datatracker.ietf.org/doc/html/rfc6455#section-5.5.3) allows ping and pong frames to have payloads (up to 125 bytes), and requires that a pong for a ping contain the same payload as the ping. However, the current websocket/af API does not allow sending payloads with ping and pong frames:

https://github.com/anmonteiro/websocketaf/blob/248a2cb0dcffa51996c3ad7643577dce75d67454/lib/websocketaf.mli#L151-L152

I actually don't know if ping/pong payloads are used in practice.

**Comment by anmonteiro** [comment]
fixed in https://github.com/anmonteiro/websocketaf/pull/54
