### ISSUE TITLE
Websocketaf.Client_connection.input_handlers and Server_connection.input_handlers not equal

### ISSUE THREAD

**Issue by aantron** [anmonteiro/httpun-ws#39]
The type checker does not admit their equality, even though they are structurally identical:

https://github.com/anmonteiro/websocketaf/blob/248a2cb0dcffa51996c3ad7643577dce75d67454/lib/websocketaf.mli#L188-L190

https://github.com/anmonteiro/websocketaf/blob/248a2cb0dcffa51996c3ad7643577dce75d67454/lib/websocketaf.mli#L229-L231

I think the type either needs to be defined in one place, or there needs to be an `= Client_connection.input_handlers` at `Server_connection.input_handlers`. Or is this lack of equality deliberate?

**Comment by anmonteiro** [comment]
fixed in https://github.com/anmonteiro/websocketaf/pull/47
