### ISSUE TITLE
digestif virtual library compat

### ISSUE THREAD

**Issue by joprice** [anmonteiro/httpun-ws#59]
I ran into an issue when using this library alongside another that chose the `digestif.c` as the implementation for digestif. Should all libraries avoid selecting the concrete implementation, leaving it up to the consumer, or is there a reason that the ocaml one is required for this lib?  https://github.com/anmonteiro/websocketaf/blob/aa6a1472926ac496b3403a0dafb0360a1bb32623/eio/dune#L4

**Comment by anmonteiro** [comment]
absolutely. fixing this in #67
