### ISSUE TITLE
[BUG] payloads of >64K are cut off at the beginning

### ISSUE THREAD

**Issue by eWert-Online** [anmonteiro/httpun-ws#62]
I am trying to use httpun-ws as a websocket client (through the latest master version of piaf).
When recieving messages with a length of >= 64K, the message gets cut off at the beginning.

I investigated a bit and I think the error is originating from the `payload_offset_of_bits` function, which maybe computes the length offset too large.

I added a few logs, which give me the following values:

```
payload length: 66225

initial_offset: 2
mask_offset: 0
length_offset: 32
```

The length_offset seems a bit excessive, as for smaller messages it is `0` or `2`.

The length computed with `let length = bits land 0b01111111 in` is "127". As soon as I reduce the length of the message to less than 64K (so the length is "126" or less), everything works fine.

**Comment by eWert-Online** [comment]
When changing the computation of the length offset to this...

```ml
let length_offset  =
  let length = bits land 0b01111111 in
  if length = 127 then 8
  else if length = 126 then 2
  else 0
in
```

...everything seems to be working fine. I don't know if this is a good solution though 😄

**Comment by anmonteiro** [comment]
Thanks, I'll have to take a closer look at this and #63.
