### ISSUE TITLE
File "eio/gluten_eio.ml", line 132, characters 16-22: Assertion failed

### ISSUE THREAD

**Issue by copy** [anmonteiro/httpun-ws#65]
Running the echo server example and connecting with chromium's built-in websocket, we get:

```
dune exec examples/eio/echo_server.exe
Fatal error: exception File "examples/eio/echo_server.ml", line 71, characters 65-71: Assertion failed
```

Replacing `on_error:(fun _ -> assert false)` with `on_error:(fun e -> raise e)` then yields:

```
Fatal error: exception File "lib/server_connection.ml", line 81, characters 4-10: Assertion failed
```

Finally, by replacing that `assert false` with a `raise exn` the error becomes:

```
Fatal error: exception File "eio/gluten_eio.ml", line 132, characters 16-22: Assertion failed
```

**Comment by copy** [comment]
Nevermind, I was using wss://  🤦

**Comment by anmonteiro** [comment]
Thanks for the report. I still think this is an issue insofar as you hit an `assert false` where we should likely fall through to closing the connection
